version: '3.9'

services:
  web:
    build: .
    container_name: flask_app
    ports:
      - "805100"
    depends_on:
      - db
    environment:
      FLASK_ENV: production
      DATABASE_URL: ${DATABASE_URL}

  db:
    image: postgres:16
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: